food/urls.py
from . import views
from django.urls import path,include
app_name='food'
urlpatterns = [
    
    #food/
    path('',views.IndexClassView.as_view(),name='index'),
    #path('',views.index,name='index'),
    #food/
    #path('<int:item_id>/',views.detail,name='detail'),
    #path('<int:pk>',views.DetailView.as_view(),name='detail'),
    path('item/<int:item_id>/', views.FoodDetailView.as_view(), name='detail'), # Using class based 
    path('item/',views.item,name='item'),
    #add item
    path('add/',views.create_item,name='create_item'),
    #path('add/',views.CreatItem.as_view(),name='create_item'), #usnigclass based
    #edit item
    path('update/<int:id>/', views.update_item, name='update_item'),
    path('delete/<int:id>/',views.delete_item,name='delete_item'),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
    path('',include('users.urls')),
]

users/urls.py
from django.urls import path
from users import views as user_views
from django.contrib.auth import views as authenticatios_views
from django.conf import settings
from django.conf.urls.static import static
app_name='users'
urlpatterns = [
    path('register/',user_views.register,name='register'),
    path('login/',authenticatios_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',authenticatios_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('profile/',user_views.profilepage,name='profile'),
    # path('login/',user_views.login,name='login'),
    # path('logout/',user_views.logout,name='logout'),
]


urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.

class Item(models.Model):           #this is like a table in mysql

    def __str__(self) -> str:
        return self.item_name
    user_name=models.ForeignKey(User,on_delete=models.CASCADE,default=1)
    item_name=models.CharField(max_length=200)
    item_desc=models.CharField(max_length=200)
    item_price=models.IntegerField()
    item_image=models.CharField(max_length=500,default='https://cdn-icons-png.flaticon.com/512/2737/2737035.png')


    def get_absolute_url(self):
        return reverse('food:detail',kwargs={'pk':self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

def user_profile_image_default():
    return r'C:\Users\Basse\Desktop\profilepic.jpg'

class Profile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE)
    image=models.ImageField(default='profilepic.jpg',upload_to='profile_pictures')
    location=models.CharField(max_length=100)

    def __str__(self) -> str:
        return self.user.username

food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model=Item
        fields=['item_name','item_desc','item_price','item_image']
        

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegiserForm(UserCreationForm):
    email=forms.EmailField()
    class Meta:
        model=User
        fields=['username','email','password1','password2']

food/views.py
from django.forms.models import BaseModelForm
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
# Create your views here.

def index(request):
    item_list = Item.objects.all()
    #template = loader.get_template('food/index.html')
    context={
        'item_list':item_list,

    }
    #return HttpResponse(template.render(context,request))
    return render(request,'food/index.html',context)

class IndexClassView(ListView): #class based 
    model=Item
    template_name='food/index.html'
    context_object_name='item_list'

def item(request):
    return HttpResponse('<h1>This is an item View</h1>')

def detail(request,item_id):
    item =Item.objects.get(pk=item_id)
    context= {
        'item':item,
    }
    return render(request,'food/detail.html',context)



class FoodDetailView(DetailView):
    model = Item
    template_name = 'food/detail.html'
    context_object_name = 'item'
    pk_url_kwarg = 'item_id'

   

#Add itemA""""" """"""
def create_item(request):
    form=ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('food:index')
    return render(request,'food/item-form.html',{'form':form})

#add item useing calss based
class CreatItem(CreateView):
    model=Item
    fields=['item_name','item_desc','item_price','item_image']
    template_name='food/item-form.html'

    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        return super().form_valid(form)


#Update exsist item

def update_item(request, id):
    item = Item.objects.get(id=id)
    if request.method == 'POST':
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('food:index')
    else:
        form = ItemForm(instance=item)
    return render(request, 'food/item-form.html', {'form': form, 'item': item})

#Delete item
def delete_item(request,id):
    item=Item.objects.get(id=id)
    if request.method =='POST':
        item.delete()
        return redirect('food:index')
    return render(request,'food/delete-item.html',{'item':item})

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm 
from django.contrib import messages
from .forms import RegiserForm
# Create your views here.

def register(request):
    if request.method == 'POST':
        form = RegiserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome {username}')
            return redirect('users:login')
    else:
        form = RegiserForm()
    return render(request, 'users/register.html', {'form': form})
 
# def login(request):
#     context={}
#     return render(request,'users/login.html',context)
# def logout(request):
#     context={}
#     return render(request,'users/logout.html',context)

def profilepage(request):
    return render(request,'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</head>
<body>
    <style>
        /* Add a class to the body to give space for the fixed navbar */
        body {
            padding-top: 70px; /* Add top padding to create space for the navbar */
            display: flex;
            flex-direction: column;
            min-height: 100vh; /* Ensure the body takes up at least the full viewport height */
            margin: 0; /* Remove default margin to prevent extra space */
        }
        .main-content {
            flex: 1; /* Allow the main content to expand and take remaining space */
        }
        .invoice {
            background-color: #f5f5f5;
            
            margin-top: auto;
            text-align: center;
        }
        .navbar {
            position: fixed; /* Fix the navbar position */
            top: 0; /* Position it at the top */
            width: 100%; /* Take up the full width */
            display: flex;
            justify-content: space-between;
            align-items: center;
            background-color: #ffc107;
            padding: 10px;
            font-family: Arial, sans-serif;
            z-index: 999; /* Ensure the navbar appears above other elements */
        }
    
        .navbar .navbar-brand {
            font-size: 24px;
            color: #660b0b;
            text-transform: uppercase;
            font-weight: bold;
            text-decoration: none;
        }
    
        .navbar .nav-items {
            display: flex;
        }
    
        .navbar .nav-item {
            margin-right: 10px;
        }
    
        .navbar .nav-item:last-child {
            margin-right: 0;
        }
    
        .navbar .nav-item a {
            color: #333;
            text-decoration: none;
            padding: 8px 12px;
            border-radius: 5px;
            font-weight: bold;
        }
    
        .navbar .nav-item.admin-link {
            background-color: #4CAF50;
            color: white;
        }
        navbar .nav-item.registeration-link {
            background-color: #4CAF50;
            color: white;
        }
    
        .navbar .nav-item a:hover {
            background-color: #f5f5f5;
        }
        .container{
            color: rgb(65, 136, 0);
            border: #ffc107;
            border-color: #f5f5f5;
            border-radius: 2px;
            font-style: italic;
            font-size: large;

        }
        span{
            color: #2000d6;
            font-style:initial;
            font-weight: bold;
        }
        .span-msg
        {
            font-size: large;
            background-origin: padding-box;
        }
        .six h1 {
            text-align: center;
            color:#222; font-size:30px; font-weight:400;
            text-transform: uppercase;
            word-spacing: 1px; letter-spacing:2px; color:#c50000;
        }
.six h1 span {
  line-height:2em; padding-bottom:15px;
  text-transform: none;
  font-size:.7em;
  font-weight: normal;
  font-style: italic; font-family: "Playfair Display","Bookman",serif;
  color:#999; letter-spacing:-0.005em; word-spacing:1px;
  letter-spacing:none;
}
.six h1:after, .six h1:before {
  position: absolute;
  left: 0;
  bottom: 0;
  width: 45px;
  height: 4px;
  content: "";
  right: 45px; 
  margin:auto;
  background-color: #ccc;
}
.six h1:before { 
background-color:#d78b8b;
  left:45px; width:90px;
}
    </style>
    
    <nav class="navbar">
        <div class="six">
            <h1><a href="{% url 'food:index' %}" class="navbar-brand">FOOD APP</a>
            </h1>
          </div>
        
        <div class="nav-items">
            <div class="nav-item">
                <a href="{% url 'food:create_item' %}">Add Item</a>
            </div>
            <div class="nav-item">
                <a href="#">Delete Item</a>
            </div>
            <div class="nav-item">
                <a href="#">View Item</a>
            </div>
            <div class="nav-item registeration-link">
                 <a href="{% url 'users:register' %}">Registration</a>
            </div>
            <div class="nav-item admin-link">
                <a href="/admin/">Admin</a>
            </div>
            <div class="nav-item logging-link">
                {% if  user.is_authenticated %}
                <span class="username"> {{user.username}}</span>
                <a href="{% url 'users:logout' %}" >Logout</a>
                {% else %}
                    <a href="{% url 'users:login' %}">Login</a>
                {% endif %}
                <a href="{% url 'users:profile' %}">profile</a>
            </div>
        </div>
    </nav>  
    <div class="alert alert-{{ message.tag }}">
        {% if messages %}
            {% for message in messages %}
                <span class="msg">{{message}}</span>
            {% endfor %}
        {% endif %}
    </div>
    {% block body%}
    {% endblock %}
    <div class="invoice">
        
    </div>
    <!-- The Footer -->
    <footer class="bg-dark text-center text-white">
        <!-- Grid container -->
        <div class="container p-4 pb-0">
          <!-- Section: Social media -->
          <section class="mb-4">
            <!-- Facebook -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-facebook-f"></i
            ></a>
      
            <!-- Twitter -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-twitter"></i
            ></a>
      
            <!-- github -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://github.com/Bassel-Alawidat" role="button"
              ><i class="fab fa-google">Github</i
            ></a>
      
            <!-- Instagram -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-instagram"></i
            ></a>
      
            <!-- Linkedin -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://www.linkedin.com/in/besil-avidat-12195b233/" role="button"
              ><i class="fab fa-linkedin-in">Linkedin</i
            ></a>
      
            <!-- Github -->
            <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
              ><i class="fab fa-github"></i
            ></a>
          </section>
          <!-- Section: Social media -->
        </div>
        <!-- Grid container -->
      
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
          © 2020 Copyright:
          <a class="text-white" href="https://mdbootstrap.com/">bassel.alawidat.98.com</a>
        </div>
        <!-- Copyright -->
      </footer> 
</body>
</html>

food/templates/food/delete-item.html
{% extends 'food/base.html' %}
{% load static %}
\{% block body %}
    <link rel="stylesheet" href="{% static 'food/delete-p.css' %}">
    <form method="post" action="{% url 'food:delete_item' item.id%}">
        {% csrf_token %}p
        <div class="container">
            <h1>Are you sure you want delete {{item.item_name}}</h1>
            <br>
            <button id="btn" type="submit">
                <p id="btnText">Confirm</p>
                <div class="check-box">
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50">
                        <path fill="transparent" d="M14.1 27.2l7.1 7.2 16.7-16.8" />
                    </svg>
                </div>
            </button>
        </div>
    </form>
    

    <script type="text/javascript">
        const btn = document.querySelector("#btn");
        const btnText = document.querySelector("#btnText");

        btn.onclick = () => {
            btnText.innerHTML = "Thanks";
            btn.classList.add("active");
        };
    </script>
{% endblock %}

food/templates/food/detail.html
{% extends 'food/base.html' %}
{% load static %}
{% block body%}
<link rel="stylesheet" href="{% static 'food/cards.css' %}">
<body>
  <div class="card-hover">
    <div class="card-hover__content">
      <h3 class="card-hover__title">
        <span>{{item.item_name}}</span>
      </h3>
      <p class="card-hover__text">{{item.item_desc}}</p>
      <a href="{% url 'food:delete_item' item.id %}" >Delete</a>
      <a href="#" class="card-hover__link">
        <span>${{item.item_price}}</span>
        
        <svg fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
        </svg>        
      </a>
    </div>
    <div class="card-hover__extra">
      <h4>L <span>now</span> and get <span>40%</span> discount!</h4>
    </div>
    <img src="{{item.item_image}}" alt="">
  </div>
</body>  
{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %}
{% load static %}
{% block body %}
    
   {% for item in item_list %}
        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img class="card" height="150px" src="{{item.item_image}}" style="width: 150px; border: 1.5px solid rgb(71, 206, 17); border-radius: 5px;">
            </div>
            <div class="col-md-4">
                <h3 style="font: italic 2.1em Fira Sans, serif;">{{item.item_name}}</h3>
            </div>
            <div class="col-md-2">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
            </div>
        </div>
        <hr style="border: 2px solid pink;">
    {% endfor %}
{% endblock %}

food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
<style>
    .form-container {
        max-width: 400px;
        margin: 20px auto; /* Adjust the margin value to create the desired spacing */
        padding: 20px;
        background-color: black;
        border: 1px solid #ccc;
        border-radius: 5px;
        flex-direction: column;
        align-items: center;
    }

    .form-container label {
        display: block;
        margin-top: 20px;
        color: white;
        font-style: italic;
    }

    .form-container input[type="text"],
    .form-container textarea {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        resize: vertical;
    }

    .form-container button[type="submit"] {
        padding: 10px 20px;
        background-color: #26e22d;
        color: rgb(0, 0, 0);
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }
    .form-container h2 {
        text-align: center;
        margin-bottom: 10px;
        color: white;
        font-size: large;
        font-style: italic;
    }
</style>
<div class="form-container">
    <h2>Add Item</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save</button>
    </form>
</div>
{% endblock %}

users/templates/users/login.html
<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">Login</button>
</form>

users/templates/users/logout.html
<h1>You have been logged out</h1>

users/templates/users/profile.html
{% block body %}
    <div class="profile-container">
        <h1>{{ user.username }}</h1>
        {% load static %}
        <img src="{{ user.profile.image.url }}" class="profile-image">
       
        
    </div>
{% endblock %}

<style>
    .profile-container {
        text-align: center;
        margin-top: 50px;
    }

    .profile-image {
        width: 200px;
        height: 200px;
        border-radius: 50%;
        object-fit: cover;
        margin-top: 20px;
    }
</style>

users/templates/users/register.html
{% extends 'food/base.html' %}
{% load static %}
{% block body %}
     <link rel="stylesheet" href="{% static 'food/register.css' %}"> 
    <form method="post" class="registration-form">
        {% csrf_token %}

        <!-- {{ form.as_p }} -->
        {{form.username.label}}
        {{form.username}}
        {{form.email.label}}
        {{form.email}}
        {{form.password1.label}}
        {{form.password1}}
        {{form.password2.label}}
        {{form.password2}}
        {{form.erorrs}}
        {% if form.errors %}
        <div class="form-errors">
            <h2>Form Errors:</h2>
            <ul>
                {% for field in form %}
                    {% if field.errors %}
                        <li>{{ field.label }}: {{ field.errors|join:", " }}</li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <br>
        <button type="submit">Register</button>
    </form>
    
{% endblock %}